// ─── Color Themes ─────────────────────────────────────────────────────────────
export const ACCENT_COLORS = {
  blue:   "#3B7DD8",
  green:  "#27AE60",
  orange: "#E67E22",
  rose:   "#E05282",
};

// ─── Text Sizes ───────────────────────────────────────────────────────────────
export const TEXT_SIZE_MULTIPLIER = {
  small:  0.85,
  medium: 1.0,
  large:  1.18,
};

// ─── Build Theme Object ───────────────────────────────────────────────────────
export function buildTheme(isDarkMode, colorTheme) {
  const accent = ACCENT_COLORS[colorTheme] ?? ACCENT_COLORS.blue;
  return {
    bg:         isDarkMode ? "#0d0d0d" : "#f2f2f0",
    surface:    isDarkMode ? "#1a1a1a" : "#ffffff",
    surfaceAlt: isDarkMode ? "#222222" : "#e8e8e4",
    card:       isDarkMode ? "#1e1e1e" : "#ffffff",
    text:       isDarkMode ? "#f0f0f0" : "#111111",
    subText:    isDarkMode ? "#666666" : "#999999",
    border:     isDarkMode ? "#2a2a2a" : "#d8d8d4",
    accent,
    danger:  "#E05252",
    success: "#27AE60",
    warning: "#F39C12",
  };
}

// ─── Translations ─────────────────────────────────────────────────────────────
const translations = {
  english: {
    // Home
    appName:       "Montra",
    income:        "Income",
    expense:       "Expense",
    balance:       "Balance",
    noRecords:     "No records for this day",
    // Add
    addTransaction: "Add Transaction",
    amount:        "Amount",
    notes:         "Notes",
    category:      "Category",
    save:          "Save",
    searchPlace:       "Search a place...",
    fetchingLocation:  "Fetching your location...",
    confirmLocation:   "Confirm Location",
    pickLocation:      "Pick Location",
    // Profile
    profile:       "Profile",
    guestUser:     "Guest User",
    localOnly:     "Local only",
    cloudSynced:   "Cloud synced",
    preferences:   "Preferences",
    currency:      "Currency",
    account:       "Account",
    linkGoogle:    "Link Google",
    saveToCloud:   "Save data to cloud",
    helpSupport:   "Help & Support",
    faqContact:    "FAQs and contact",
    signOut:       "Sign Out",
    // Settings
    settings:        "Settings",
    appearance:      "Appearance",
    themeMode:       "Theme Mode",
    dark:            "Dark",
    light:           "Light",
    colorTheme:      "Color Theme",
    textSize:        "Text Size",
    language:        "Language",
    // Advanced
    advanced:              "Advanced",
    customDate:            "Custom Date",
    customDateSub:         "Pick any past date when adding",
    transactionDots:       "Transaction Dots",
    transactionDotsSub:    "Show dots on dates with transactions",
    enableCustomDate:      "Enable Custom Date?",
    enableDots:            "Enable Transaction Dots?",
    customDateDesc:        "This lets you pick any past date when adding a transaction.",
    transactionDotsDesc:   "This shows dots on calendar dates that have existing transactions.",
    closesIn:              "Closes in",
    dontShowAgain:         "Don't show again",
    okEnable:              "OK, Enable it",
    // Analytics
    analytics:     "Analytics",
    week:          "Week",
    month:         "Month",
    year:          "Year",
    // Help & Support
    helpSupportTitle:    "Help & Support",
    hereToHelp:          "We're here to help",
    heroSub:             "Browse the FAQ or drop us an email — we reply within 24 hours.",
    frequentlyAsked:     "Frequently Asked",
    contactUs:           "Contact Us",
    about:               "About",
    formNote:            "Opens your mail app with a pre-filled message to",
    subjectPlaceholder:  "Subject",
    messagePlaceholder:  "Describe your issue or question...",
    sendMessage:         "Send Message",
    openingMail:         "Opening mail…",
    missingInfo:         "Missing Info",
    missingInfoMsg:      "Please fill in both the subject and message.",
    noEmailApp:          "No Email App",
    noEmailAppMsg:       "We couldn't find a mail app. Please email us at support@moneytracker.app",
    errorGeneric:        "Something went wrong. Please try again.",
    // FAQ
    faq1Q: "How do I add a transaction?",
    faq1A: "Tap the Add tab at the bottom. Enter the amount, pick a category, add an optional note or photo, then tap Save. Your balance updates instantly.",
    faq2Q: "What is Advanced Mode?",
    faq2A: "Advanced Mode unlocks two extra features — Custom Date and Transaction Dots. You can enable each one separately in Settings → Advanced.",
    faq3Q: "What is Custom Date?",
    faq3A: "When Custom Date is on, a date picker appears in the Add screen so you can log a transaction on any past date — useful if you forgot to record something earlier.",
    faq4Q: "What are Transaction Dots?",
    faq4A: "When Transaction Dots is on, a small dot appears on dates in the calendar picker that already have transactions recorded, so you can quickly see which days have activity.",
    faq5Q: "Is my data safe?",
    faq5A: "Guest accounts store data locally on your device only. Linking a Google account syncs everything securely to the cloud so you never lose it.",
    faq6Q: "How do I switch currencies?",
    faq6A: "Currency switching is coming soon! We're working on full multi-currency support. Stay tuned for updates in the next release.",
    faq7Q: "Can I export my transactions?",
    faq7A: "Export is coming soon! We're working on CSV and PDF export. Stay tuned for updates in the next release.",
    faq8Q: "How do I delete a transaction?",
    faq8A: "Tap any transaction to open the Details screen, then tap the Delete button. You'll be asked to confirm before it's removed.",
    faq9Q: "Does Montra work offline?",
    faq9A: "Yes! Montra works fully offline. Any transactions you add while offline are saved locally and automatically synced to the cloud when your connection is restored.",
    // About rows
    aboutAppName:    "App Name",
    aboutVersion:    "Version",
    aboutDeveloper:  "Developer",
    aboutEmail:      "Support Email",
    aboutPlatform:   "Platform",
    // Offline / Online modals
    offlineTitle:        "You're Offline",
    offlineMsg:          "No internet connection detected. Your data is safe — changes will sync automatically when you're back online.",
    offlineMsgPending:   "No internet connection detected. You have {count} pending change{s} that will sync when you're back online.",
    onlineTitle:         "Back Online",
    onlineMsg:           "Your connection has been restored. Any pending changes are being synced now.",
    modalClosesIn:       "This modal will close in {count} second{s}",
    gotIt:               "Got it",
    great:               "Great",
  },
  filipino: {
    // Home
    appName:       "Montra",
    income:        "Kita",
    expense:       "Gastos",
    balance:       "Balanse",
    noRecords:     "Walang talaan para sa araw na ito",
    // Add
    addTransaction: "Magdagdag ng Transaksyon",
    amount:        "Halaga",
    notes:         "Mga Tala",
    category:      "Kategorya",
    save:          "I-save",
    searchPlace:       "Maghanap ng lugar...",
    fetchingLocation:  "Kinukuha ang iyong lokasyon...",
    confirmLocation:   "Kumpirmahin ang Lokasyon",
    pickLocation:      "Pumili ng Lokasyon",
    // Profile
    profile:       "Profile",
    guestUser:     "Bisita",
    localOnly:     "Lokal lamang",
    cloudSynced:   "Naka-sync sa cloud",
    preferences:   "Mga Kagustuhan",
    currency:      "Pera",
    account:       "Account",
    linkGoogle:    "I-link ang Google",
    saveToCloud:   "I-save ang data sa cloud",
    helpSupport:   "Tulong at Suporta",
    faqContact:    "FAQs at makipag-ugnayan",
    signOut:       "Mag-sign Out",
    // Settings
    settings:        "Mga Setting",
    appearance:      "Hitsura",
    themeMode:       "Mode ng Tema",
    dark:            "Madilim",
    light:           "Maliwanag",
    colorTheme:      "Kulay ng Tema",
    textSize:        "Laki ng Teksto",
    language:        "Wika",
    // Advanced
    advanced:              "Advanced",
    customDate:            "Custom na Petsa",
    customDateSub:         "Pumili ng sariling petsa",
    transactionDots:       "Mga Tuldok ng Transaksyon",
    transactionDotsSub:    "Tuldok sa may transaksyon",
    enableCustomDate:      "Paganahin ang Custom na Petsa?",
    enableDots:            "Paganahin ang Mga Tuldok ng Transaksyon?",
    customDateDesc:        "Pinapayagan kang pumili ng sariling petsa kapag nagdadagdag ng transaksyon.",
    transactionDotsDesc:   "Nagpapakita ng mga tuldok sa kalendaryo sa mga petsa na may mga transaksyon.",
    closesIn:              "Magsasara sa loob ng",
    dontShowAgain:         "Huwag ipakita muli",
    okEnable:              "Sige, I-enable",
    // Analytics
    analytics:     "Analytics",
    week:          "Linggo",
    month:         "Buwan",
    year:          "Taon",
    // Help & Support
    helpSupportTitle:    "Tulong at Suporta",
    hereToHelp:          "Nandito kami para tumulong",
    heroSub:             "Tingnan ang FAQ o mag-email sa amin — sumasagot kami sa loob ng 24 na oras.",
    frequentlyAsked:     "Mga Madalas na Tanong",
    contactUs:           "Makipag-ugnayan",
    about:               "Tungkol Sa App",
    formNote:            "Magbubukas ng mail app na may pre-filled na mensahe para sa",
    subjectPlaceholder:  "Paksa",
    messagePlaceholder:  "Ilarawan ang iyong isyu o tanong...",
    sendMessage:         "Ipadala ang Mensahe",
    openingMail:         "Binubuksan ang mail…",
    missingInfo:         "Kulang ang Impormasyon",
    missingInfoMsg:      "Pakipunan ang paksa at mensahe.",
    noEmailApp:          "Walang Email App",
    noEmailAppMsg:       "Hindi mahanap ang mail app. Mag-email sa support@moneytracker.app",
    errorGeneric:        "May nangyaring mali. Subukan muli.",
    // FAQ
    faq1Q: "Paano magdagdag ng transaksyon?",
    faq1A: "I-tap ang Add tab sa ibaba. Ilagay ang halaga, pumili ng kategorya, magdagdag ng tala o larawan kung gusto, tapos i-tap ang I-save. Agad na ma-a-update ang iyong balanse.",
    faq2Q: "Ano ang Advanced Mode?",
    faq2A: "Ina-unlock ng Advanced Mode ang dalawang karagdagang feature — Custom na Petsa at Mga Tuldok ng Transaksyon. Maaari mong i-enable ang bawat isa nang hiwalay sa Settings → Advanced.",
    faq3Q: "Ano ang Custom na Petsa?",
    faq3A: "Kapag naka-on ang Custom na Petsa, lalabas ang date picker sa Add screen para makapag-log ka ng transaksyon sa anumang sariling petsa — kapaki-pakinabang kung nakalimutan mong i-record ang isang bagay nang mas maaga.",
    faq4Q: "Ano ang Mga Tuldok ng Transaksyon?",
    faq4A: "Kapag naka-on ang Mga Tuldok ng Transaksyon, may maliit na tuldok na lalabas sa mga petsa sa calendar picker na may naka-record nang mga transaksyon, para madali mong makita kung aling mga araw ang may aktibidad.",
    faq5Q: "Ligtas ba ang aking data?",
    faq5A: "Ang mga guest account ay nag-iimbak ng data nang lokal sa iyong device lamang. Ang pag-link ng Google account ay nag-i-sync ng lahat nang ligtas sa cloud para hindi mo ito mawala.",
    faq6Q: "Paano ko mababago ang pera?",
    faq6A: "Malapit nang dumating ang pagpapalit ng pera! Nagtatrabaho kami sa buong suporta ng multi-currency. Abangan ang mga update sa susunod na release.",
    faq7Q: "Maaari ko bang i-export ang aking mga transaksyon?",
    faq7A: "Malapit nang dumating ang export! Nagtatrabaho kami sa CSV at PDF export. Abangan ang mga update sa susunod na release.",
    faq8Q: "Paano ko matatanggal ang isang transaksyon?",
    faq8A: "I-tap ang anumang transaksyon para buksan ang Details screen, tapos i-tap ang Delete button. Hihilingin sa iyo na kumpirmahin bago ito matanggal.",
    faq9Q: "Gumagana ba ang Montra nang offline?",
    faq9A: "Oo! Ganap na gumagana ang Montra nang offline. Ang mga transaksyong idadagdag mo habang offline ay nai-save nang lokal at awtomatikong nai-sync sa cloud kapag naibalik ang iyong koneksyon.",
    // About rows
    aboutAppName:    "Pangalan ng App",
    aboutVersion:    "Bersyon",
    aboutDeveloper:  "Developer",
    aboutEmail:      "Support Email",
    aboutPlatform:   "Platform",
    // Offline / Online modals
    offlineTitle:        "Naka-offline Ka",
    offlineMsg:          "Walang internet connection na na-detect. Ligtas ang iyong data — awtomatikong mag-si-sync ang mga pagbabago kapag bumalik ka online.",
    offlineMsgPending:   "Walang internet connection na na-detect. Mayroon kang {count} nakabinbing pagbabago{s} na mag-si-sync kapag bumalik ka online.",
    onlineTitle:         "Bumalik Online",
    onlineMsg:           "Naibalik na ang iyong koneksyon. Ang mga nakabinbing pagbabago ay naka-sync na ngayon.",
    modalClosesIn:       "Magsasara ang modal na ito sa loob ng {count} segundo{s}",
    gotIt:               "Naintindihan",
    great:               "Ayos!",
  },
};

export function t(language, key) {
  return translations[language]?.[key] ?? translations.english[key] ?? key;
}