import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

Deno.serve(async (req) => {
  const url = new URL(req.url);
  const id = url.searchParams.get("id");

  if (!id) {
    return new Response("Missing transaction ID", { status: 400 });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const { data, error } = await supabase
    .from("transactions")
    .select("*")
    .eq("id", id)
    .single();

  if (error || !data) {
    return new Response("Transaction not found", { status: 404 });
  }

  const isIncome = data.type === "income";
  const color = isIncome ? "#2ECC71" : "#FF6B6B";
  const sign = isIncome ? "+" : "-";
  const amount = data.amount?.toLocaleString(undefined, { minimumFractionDigits: 2 });
  const date = data.created_at ? new Date(data.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "N/A";
  const time = data.created_at ? new Date(data.created_at).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" }) : "N/A";

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Transaction Receipt</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #f4f4f4; font-family: -apple-system, BlinkMacSystemFont, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; padding: 20px; }
    .card { background: #fff; border-radius: 24px; padding: 40px 32px; width: 100%; max-width: 400px; box-shadow: 0 8px 40px rgba(0,0,0,0.08); }
    .label { text-align: center; font-size: 11px; font-weight: 800; letter-spacing: 2px; color: #999; margin-bottom: 24px; }
    .type-pill { display: inline-block; background: ${color}22; color: ${color}; font-size: 11px; font-weight: 800; letter-spacing: 1.5px; padding: 5px 14px; border-radius: 20px; margin-bottom: 12px; }
    .amount { font-size: 52px; font-weight: 900; color: #000; letter-spacing: -2px; margin-bottom: 4px; }
    .hero { text-align: center; margin-bottom: 28px; }
    .divider { border: none; border-top: 1px solid #eee; margin: 24px 0; }
    .row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; }
    .row-label { color: #999; font-size: 13px; }
    .row-value { color: #000; font-size: 13px; font-weight: 600; text-align: right; max-width: 60%; }
    .footer { text-align: center; color: #ccc; font-size: 11px; margin-top: 28px; }
  </style>
</head>
<body>
  <div class="card">
    <p class="label">TRANSACTION RECEIPT</p>
    <div class="hero">
      <div><span class="type-pill">${isIncome ? "↑ INCOME" : "↓ EXPENSE"}</span></div>
      <p class="amount">${sign}₱${amount}</p>
    </div>
    <hr class="divider"/>
    <div class="row"><span class="row-label">Category</span><span class="row-value">${data.parent_category} › ${data.sub_category}</span></div>
    <div class="row"><span class="row-label">Date</span><span class="row-value">${date}</span></div>
    <div class="row"><span class="row-label">Time</span><span class="row-value">${time}</span></div>
    ${data.notes ? `<div class="row"><span class="row-label">Note</span><span class="row-value">${data.notes}</span></div>` : ""}
    ${data.latitude ? `<div class="row"><span class="row-label">Location</span><span class="row-value">${data.latitude.toFixed(5)}, ${data.longitude.toFixed(5)}</span></div>` : ""}
    ${data.image_urls && data.image_urls.length > 0 ? `
    <hr class="divider"/>
    <p class="row-label" style="margin-bottom:12px;">ATTACHMENTS</p>
    <div style="display:flex;flex-wrap:wrap;gap:10px;">
      ${data.image_urls.map((url: string) => `<img src="${url}" style="width:100%;max-width:360px;border-radius:14px;object-fit:cover;" />`).join("")}
    </div>` : ""}
    <p class="footer">Generated by [App Name]</p>
  </div>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: new Headers({
      "Content-Type": "text/html; charset=utf-8",
    }),
  });
});